[env]
LIBRARY_EXTENSION = { source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "unknown", mapping = { "linux" = "so", "macos" = "dylib", "windows" = "dll", "openbsd" = "so" } }
LIBRARY_PREFIX = { source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "unknown", mapping = {"linux" = "lib", "macos" = "lib", "windows" = "", "openbsd" = "lib" } }
TEST_PLUGIN_FILENAME="wooting_analog_test_plugin"

[tasks.install-plugin]
script_runner = "@shell"
script = [
'''
echo "Installing test plugin to ${PLUGIN_INSTALL_PATH}/wooting-test-plugin"
sudo install -Dm755 "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/debug/${LIBRARY_PREFIX}${TEST_PLUGIN_FILENAME}.${LIBRARY_EXTENSION}" "${PLUGIN_INSTALL_PATH}/wooting-test-plugin/${LIBRARY_PREFIX}${TEST_PLUGIN_FILENAME}.${LIBRARY_EXTENSION}"
'''
]
dependencies = ["build"]

[tasks.install-plugin.linux]
env = {PLUGIN_INSTALL_PATH="/usr/local/share/WootingAnalogPlugins"}

[tasks.install-plugin.windows]
env = {PLUGIN_INSTALL_PATH="C:\\Program Files\\WootingAnalogPlugins"}
script_runner = "powershell"
script_extension = "ps1"
script = [
'''
echo "Requesting admin powershell to install the test-plugin"
$command = "New-Item -ItemType 'directory' -Force '${env:PLUGIN_INSTALL_PATH}\wooting-test-plugin'; Copy-Item '${env:CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}\target\debug\${env:LIBRARY_PREFIX}${env:TEST_PLUGIN_FILENAME}.${env:LIBRARY_EXTENSION}' '${env:PLUGIN_INSTALL_PATH}\wooting-test-plugin\${env:LIBRARY_PREFIX}${env:TEST_PLUGIN_FILENAME}.${env:LIBRARY_EXTENSION}' -Force"
echo $command
Start-Process PowerShell.exe -ArgumentList $command -Wait -Verb RunAs
'''
]

[tasks.install-plugin.mac]
env = {TEST_PLUGIN_FILENAME="wooting_analog_test_plugin",PLUGIN_INSTALL_PATH="/usr/local/share/WootingAnalogPlugins"}

[tasks.pre-test]
script_runner = "@shell"
script = [
'''
mkdir -p "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/debug/test_plugin"

cp "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/debug/${LIBRARY_PREFIX}${TEST_PLUGIN_FILENAME}.${LIBRARY_EXTENSION}" "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/debug/test_plugin/${LIBRARY_PREFIX}${TEST_PLUGIN_FILENAME}.${LIBRARY_EXTENSION}"
'''
]
dependencies = ["build"]